/**
 * 将文件扩展名映射为 highlight.js 的 language 名（与 lib/index.js 中 register 名一致）。
 * 未知扩展名会原样返回，由编辑器侧用 hljs.getLanguage 校验并回退 plaintext。
 */
const EXT_TO_HLJS: Record<string, string> = {
  // JavaScript / TypeScript
  js: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  jsx: 'javascript',
  es6: 'javascript',
  ts: 'typescript',
  mts: 'typescript',
  cts: 'typescript',
  tsx: 'typescript',
  // 数据 / 配置
  json: 'json',
  jsonc: 'json',
  yaml: 'yaml',
  yml: 'yaml',
  toml: 'ini',
  ini: 'ini',
  cfg: 'ini',
  conf: 'ini',
  properties: 'properties',
  env: 'properties',
  // Web
  html: 'xml',
  htm: 'xml',
  xhtml: 'xml',
  shtml: 'xml',
  vue: 'xml',
  xml: 'xml',
  svg: 'xml',
  xsd: 'xml',
  wsdl: 'xml',
  rss: 'xml',
  atom: 'xml',
  xsl: 'xml',
  plist: 'xml',
  css: 'css',
  scss: 'scss',
  sass: 'scss',
  less: 'less',
  styl: 'stylus',
  // 文档
  md: 'markdown',
  mdown: 'markdown',
  markdown: 'markdown',
  mdx: 'markdown',
  // Shell / 脚本
  sh: 'shell',
  bash: 'shell',
  zsh: 'shell',
  fish: 'shell',
  ksh: 'shell',
  ps1: 'powershell',
  psm1: 'powershell',
  bat: 'dos',
  cmd: 'dos',
  dockerfile: 'dockerfile',
  // 数据库 / 查询
  sql: 'sql',
  mysql: 'sql',
  pgsql: 'pgsql',
  graphql: 'graphql',
  gql: 'graphql',
  // Python / JVM / .NET
  py: 'python',
  pyw: 'python',
  pyi: 'python',
  java: 'java',
  kt: 'kotlin',
  kts: 'kotlin',
  scala: 'scala',
  sc: 'scala',
  cs: 'csharp',
  fs: 'fsharp',
  fsx: 'fsharp',
  vb: 'vbnet',
  groovy: 'groovy',
  gradle: 'gradle',
  // C 族
  c: 'c',
  h: 'c',
  cc: 'cpp',
  cpp: 'cpp',
  cxx: 'cpp',
  hpp: 'cpp',
  hxx: 'cpp',
  hh: 'cpp',
  // 其他语言
  go: 'go',
  rs: 'rust',
  swift: 'swift',
  php: 'php',
  phtml: 'php',
  rb: 'ruby',
  ru: 'ruby',
  erb: 'erb',
  pl: 'perl',
  pm: 'perl',
  lua: 'lua',
  r: 'r',
  dart: 'dart',
  ex: 'elixir',
  exs: 'elixir',
  cls: 'latex',
  sty: 'latex',
  tex: 'latex',
  // 系统 / 构建
  cmake: 'cmake',
  make: 'makefile',
  makefile: 'makefile',
  mk: 'makefile',
  nginx: 'nginx',
  vim: 'vim',
  wasm: 'wasm',
  wat: 'wasm',
  // 纯文本
  txt: 'plaintext',
  text: 'plaintext',
  log: 'plaintext',
  csv: 'plaintext',
  tsv: 'plaintext',
}

export function highlightLanguageFromExtension(ext: string): string {
  const e = ext.trim().replace(/^\.+/, '').toLowerCase()
  if (!e) return 'plaintext'
  return EXT_TO_HLJS[e] ?? e
}
